// @flow

export default {
  GOOGLE_ANALYTICS_TRACKER_TRACK_SCREEN_VIEW: 'GOOGLE_ANALYTICS_TRACKER_TRACK_SCREEN_VIEW',
  GOOGLE_ANALYTICS_TRACKER_TRACK_EVENT: 'GOOGLE_ANALYTICS_TRACKER_TRACK_EVENT',
};
